- key: "the-filter?_=1"
  title: 配置 - 筛选器 - 单个筛选器
  filters:
    - title: 名称
      key: f1
  fields:
    - key: id
      title: ID
      sortable: true
    - key: title
      title: 名称
    - key: description
      title: 描述

- key: "the-filter?_=2"
  title: "配置 - 筛选器 - 多个筛选器"
  filters:
    - title: 名称
      key: f1
    - title: 描述
      key: f2
  fields:
    - key: id
      title: ID
      sortable: true
    - key: title
      title: 名称
    - key: description
      title: 描述

- key: "the-list-data-2?3"
  noWhere: "<b>请先选择筛选条件</b>"
  title: "配置 - 筛选器 - 默认不搜索"
  filters:
    - title: "条件"
      key: "f1"
      component: "String"
  fields:
    - key: "id"
      title: "ID"
      sortable: true
    - key: "a"
      title: "a"
      component: "TextTip"

- key: "the-filter?_=4"
  title: "配置 - 筛选器 - beforeApply"
  beforeApply:
    action: "get"
    args:
      key: "before"
  filters:
    - title: 名称
      key: f1
  fields:
    - key: id
      title: ID
      sortable: true
    - key: title
      title: 名称
    - key: description
      title: 描述
